<?php
/**
 * 配置文件
 */
define('TONGYI_DOMAIN','ht.5067.org');//统一平台域名
define('DAILI_DOMAIN','dl2.5067.org');//代理平台域名
define('GSHOW_DOMAIN','cd.5067.org');//微海报域名
define('TONGYI_IP','182.61.47.52');//统一平台服务器ip
define('TONGYI_JUYU_IP','172.16.0.16');//统一平台服务器ip局域网
define('TONGYI_TUISONG_JUYU_IP','172.16.0.17');//统一平台推送服务器ip局域网
define('TONGYI_TUISONG_IP','182.61.23.43');//统一平台推送服务器ip
define('TONGYI_TUISONG_DIR',"gbpen/public/customers");//统一平台推送客户文件夹路径
define('TONGYI_TUISONG_FTP_PORT',"21");//统一平台推送FTP端口
define('TONGYI_TUISONG_FTP_USER','12t');//统一平台推送FTP用户
define('TONGYI_TUISONG_FTP_PASSWORD','Db#907$LKF');//统一平台推送FTP用户
define('GBPEN_FTP',"gbpen.ftp-gz01.bcehost.com");//G名片FTP
define('GBPEN_FTP_PORT',"8010");//G名片FTP端口
define('GBPEN_FTP_USER','gbpen');//G名片FTP用户
define('GBPEN_FTP_PASSWORD','739jttts');//G名片FTP用户