<?php

return [
	'content-news' => '新闻内容',
	'content-product' => '产品内容',
	'_footer' => '底部',
	'_header' => '头部',
	'global' => '全局',
	'index' => '首页',
	'list-image' => '图片列表',
	'list-imagetext' => '图文列表',
	'list-page' => '内容单页',
	'list-page-form' => '内容单页',
	'list-text' => '文字列表',
	//'global' => '全局',
	//'style' => '基本',
	//'style_grey' => '灰色',
	//'style_black' => '黑色',
	//'style_green' => '绿色',
	//'style_yellow' => '黄色',
	//'style_orange' => '橘色',
	//'style_pink' => '粉色',
	//'style_red' => '红色',
	//'style_purple' => '紫色',
	//'style_coffee' => '咖啡',
];
